### ISSUE TITLE
04章 图片显示不正常

### ISSUE THREAD

**Issue by grejioh** [AbstProcDo/Master-Emacs-From-Scratch-with-Solid-Procedures#1]
04.Read-a-Book-In-a-Serioius-Way.org 大量图片显示不正常
![2021-02-01 20 20 57 github com 6fa48798a2cf](https://user-images.githubusercontent.com/43024589/106458218-09c55c80-64cb-11eb-8e1a-56bf99d8cbe2.png)

**Comment by AbstProcDo** [comment]
万分感谢，逐一修复好了。

**Comment by AbstProcDo** [comment]
图片较多，读起来会跳来跳去，推荐这个插件浏览 https://github.com/casouri/iscroll/blob/master/iscroll.el
